spring:
  application:
    name: yifan-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s
      routes:
        - id: yifan-instance
          uri: lb://YIFAN-INSTANCE
          order: 0
          predicates:
            - Path=/yifan-instance/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo,Default-Bar
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
      #      discovery:
#        locator:
#          enabled: false
#          lower-case-service-id: false
      default-filters:
        - Elapsed=true
        - name:
            RequestRateLimiter
          args:
            key-resolver: '#{@remoteAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 500
            redis-rate-limiter.burstCapacity: 500
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
#  command:
#    default:
#      execution:
#        timeout:
#          enabled=true
#        isolation:
#          thread:
#            timeoutInMilliseconds=10000

server:
  port: 2001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8990/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug


